DROP DATABASE IF EXISTS notes;

CREATE DATABASE notes;

\c notes

-- Create users table
CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(20) PRIMARY KEY,
    hashed_password VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL
);

-- Create notes table
CREATE TABLE IF NOT EXISTS notes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    owner_username VARCHAR(20) NOT NULL,
    FOREIGN KEY (owner_username) REFERENCES users(username) ON DELETE CASCADE
);

-- Insert sample data into users table
INSERT INTO users (username, hashed_password, email, first_name, last_name) VALUES
    ('john_doe', '<hashed_password>', 'john@example.com', 'John', 'Doe'),
    ('jane_smith', '<hashed_password>', 'jane@example.com', 'Jane', 'Smith');

-- Insert sample data into notes table
-- Assuming 'owner_username' refers to existing usernames in the users table
INSERT INTO notes (title, content, owner_username) VALUES
    ('Note 1', 'Content of note 1', 'john_doe'),
    ('Note 2', 'Content of note 2', 'jane_smith');
